vim.cmd('source ~/.config/nvim/vimrc')

require("cmp-setup")
require("go-setup")
require("treesitter-setup")
require("luasnip-setup")
require("base16")
require("neo-tree-setup")
require("telescope-setup")
--require("minimal_init")
