filetype plugin indent on          " Load plugins according to detected filetype.
syntax on                          " Enable syntax highlighting.

call plug#begin()
  Plug 'tpope/vim-vinegar'
  Plug 'nvim-neo-tree/neo-tree.nvim'
  Plug 'nvim-lua/plenary.nvim'
  Plug 'nvim-tree/nvim-web-devicons'
  Plug 'MunifTanjim/nui.nvim'
  Plug 'scrooloose/nerdcommenter'

  Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}

  " https://github.com/junegunn/vim-plug/issues/1107#issuecomment-911155500
  let g:go_update_command = ":lua require('go.install').update_all()"
  Plug 'ray-x/go.nvim', {'do': g:go_update_command}
  Plug 'ray-x/guihua.lua'
  Plug 'mfussenegger/nvim-dap'
  Plug 'rcarriga/nvim-dap-ui'
  Plug 'theHamsta/nvim-dap-virtual-text'

  Plug 'nvim-lua/plenary.nvim'
  Plug 'nvim-telescope/telescope.nvim', { 'tag': '0.1.1' }
  Plug 'nvim-telescope/telescope-fzf-native.nvim', { 'do': 'make' }
  Plug 'BurntSushi/ripgrep'

  Plug 'semanser/vim-outdated-plugins'

  Plug 'neovim/nvim-lspconfig'
  Plug 'hrsh7th/cmp-nvim-lsp'
  Plug 'hrsh7th/cmp-buffer'
  Plug 'hrsh7th/cmp-path'
  Plug 'hrsh7th/cmp-cmdline'
  Plug 'hrsh7th/nvim-cmp'
  Plug 'L3MON4D3/LuaSnip', {'do': 'make && make jsregexp && make install_jsregexp'}
  Plug 'saadparwaiz1/cmp_luasnip'
  Plug 'rafamadriz/friendly-snippets'
  Plug 'nvim-lua/plenary.nvim'
  Plug 'petertriho/cmp-git'

  Plug 'airblade/vim-gitgutter'
  Plug 'tpope/vim-fugitive'

  Plug 'vim-airline/vim-airline'
  Plug 'vim-airline/vim-airline-themes'

  Plug 'tinted-theming/base16-vim', {'commit': '88a1e73e5358fefe0288538e6866f99d5487c5a0'}

  Plug 'williamboman/mason.nvim'
  Plug 'williamboman/mason-lspconfig.nvim'

  Plug 'jose-elias-alvarez/null-ls.nvim'
call plug#end()

" nerdcomenter
" Comment/uncomment lines
map <leader>/ <plug>NERDCommenterToggle

" outdated-plugins
let g:outdated_plugins_silent_mode = 1

" vim-airline
let g:airline_powerline_fonts = 1
let g:airline_inactive_collapse=1
let g:airline_stl_path_style = 'short'
let g:airline#extensions#branch#enabled=1

" vim-gitgutter
highlight! link SignColumn LineNr

function! BufferRootDir()
  let l:root_dir = system('git -C '.expand('%:p:h').' rev-parse --show-toplevel 2> /dev/null')[:-2]

  if v:shell_error == 0
    return l:root_dir
  endif

  return resolve(expand('%:p:h'))
endfunction

autocmd BufEnter * if BufferRootDir() !~ ':/' | execute ':lcd' BufferRootDir() | endif
