filetype plugin indent on          " Load plugins according to detected filetype.
syntax on                          " Enable syntax highlighting.

function! TreesitterPostAction(info)
  " info is a dictionary with 3 fields
  " - name:   name of the plugin
  " - status: 'installed', 'updated', or 'unchanged'
  " - force:  set on PlugInstall! or PlugUpdate!
  execute "TSInstall all"
  execute "TSUpdate all"
endfunction

call plug#begin()
  Plug 'semanser/vim-outdated-plugins'
  Plug 'nvim-lua/plenary.nvim'

  Plug 'nvim-tree/nvim-tree.lua'
  Plug 'nvim-tree/nvim-web-devicons' " optional

  Plug 'numToStr/Comment.nvim'

  Plug 'nvim-treesitter/nvim-treesitter', {'do': function('TreesitterPostAction')}
  Plug 'nvim-treesitter/playground'

  Plug 'rcarriga/nvim-notify'
  Plug 'mrded/nvim-lsp-notify'

  Plug 'mfussenegger/nvim-dap'
  Plug 'rcarriga/nvim-dap-ui'
  Plug 'folke/neodev.nvim' 
  Plug 'theHamsta/nvim-dap-virtual-text'
  Plug 'leoluz/nvim-dap-go'

  Plug 'nvim-telescope/telescope.nvim',
  Plug 'nvim-telescope/telescope-fzf-native.nvim', { 'do': 'make' }
  Plug 'nvim-telescope/telescope-ui-select.nvim'
  Plug 'nvim-telescope/telescope-live-grep-args.nvim'

  Plug 'hrsh7th/nvim-cmp'
  Plug 'hrsh7th/cmp-nvim-lsp'
  Plug 'hrsh7th/cmp-nvim-lsp-document-symbol'
  Plug 'hrsh7th/cmp-nvim-lsp-signature-help'
  Plug 'hrsh7th/cmp-buffer'
  Plug 'hrsh7th/cmp-path'
  Plug 'hrsh7th/cmp-cmdline'
  Plug 'hrsh7th/cmp-nvim-lua'
  Plug 'saadparwaiz1/cmp_luasnip'
  Plug 'petertriho/cmp-git'

  Plug 'L3MON4D3/LuaSnip', {'do': 'make install_jsregexp'}
  Plug 'L3MON4D3/cmp-luasnip-choice'
  " Plug 'rafamadriz/friendly-snippets'
  " Plug 'honza/vim-snippets'

  Plug 'TimUntersberger/neogit'
  Plug 'lewis6991/gitsigns.nvim'
  Plug 'sindrets/diffview.nvim'

  Plug 'nvim-lua/lsp-status.nvim'
  Plug 'nvim-lualine/lualine.nvim'
  Plug 'RRethy/nvim-base16'

  Plug 'neovim/nvim-lspconfig'
  Plug 'jose-elias-alvarez/null-ls.nvim'
  Plug 'williamboman/mason.nvim'
  Plug 'williamboman/mason-lspconfig.nvim'
  Plug 'jay-babu/mason-null-ls.nvim'
  Plug 'davidmh/cspell.nvim'

  Plug 'folke/lsp-trouble.nvim'

  Plug 'folke/which-key.nvim'

  Plug 'nvim-neotest/neotest'
  " pinning due to https://github.com/nvim-neotest/neotest-go/issues/47
  " Plug 'nvim-neotest/neotest-go'
  Plug 'zankich/neotest-go', {'branch': 'gh-issue-47'}
call plug#end()

" outdated-plugins
let g:outdated_plugins_silent_mode = 1
