vim.cmd('source ~/.config/nvim/vimrc')

require("core.options")
require("core.util")
require("core.base16")
require("core.mason")

require("core.cmp")
require("core.go")
require("core.luasnip")
require("core.telescope")
require("core.null-ls")
require("core.comment")
require("core.lualine")
require("core.nvim-tree")
require("core.treesitter")
--require("core.lsp")
--require("core.neo-tree")
