vim.cmd('source ~/.config/nvim/vimrc')

require("core.cmp")
require("core.go")
require("core.treesitter")
require("core.luasnip")
require("core.base16")
require("core.neo-tree")
require("core.telescope")
require("core.util")
require("core.options")
require("core.mason")
require("core.null-ls")
--require("core.lsp")
